// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:genai_mobile/dao/hive_adapters.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(DocumentAdapter());
    registerAdapter(DocumentTypeAdapter());
    registerAdapter(PromptAdapter());
  }
}
